### ISSUE TITLE
Perl library mismatch

### ISSUE THREAD

**Issue by algebravic** [apaffenholz/homebrew-polymake#6]
I installed polymake via
brew tap apaffenholz/polymake
brew install polymake

on an iMac with Intel hardware, running Ventura 13.2.1.  When I try to run polymake, get the following error:

polymake --help
IO.c: loadable library and perl binaries are mismatched (got first handshake key 0xf880080, needed 0xf900080)

My perl is 5.36.0 from homebrew.

Any suggestions?

**Comment by apaffenholz** [comment]
Not really. I can only guess. 

There error probably comes from a version mismatch between a perl module and its binary component. 

Are some Modules installed locally in $HOME/perl5? Are they for a different version of perl (e.g. the system version instead of the homebrew version)? DO you set any evn variables in .zshrc that may infuence this (PERL5LIB, PERL_LOCAL_LIB_ROOT)?

**Comment by apaffenholz** [comment]
This will hopefully be fixed with the new version.
